---
title: "First Knit"
author: "April Parry"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended High school at Lancaster high and I'm going to graduate this upcoming June. English compared to math is more easier due to the fact it doesn't include equations. The subject I did best in is in English and in science. I prefer those two over math any time.    

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I do have a laptop at home, which is a lenovo. On a scale 1 to ten I will say that my computer knowlege sits around a 6. I know some computer stuff but obviously not all. Also I do have internet access at home and it run's completely fine.   
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called by my name April. Since I don't my name can be shorten into a nickname.   
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to achieve my associates and transfer to a university in or out of state. The college subject I'm interested in is art, painting anything that is related to art. Since my major is computer animation and I want to become an animator.   
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have never been to any foreign countries, but I do want to visit a city. I would like to go to Hawaii Honolulu and Nyc. I have never been in the military or in any branch. If I got drafted the branch I would choose is the Navy. 
     
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I haven't taken any math in college, this is my first math. And I know it satisfies the general education on both transfer and for my degree.  For my future plans I need to attain a B or higher, so that I could be able to transfer out or in of state.   
   
 






  




